// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const deleteDevicesByDEPAndSerials = `-- name: DeleteDevicesByDEPAndSerials :exec
DELETE FROM
    dep_devices
WHERE
    dep_name = ?
    AND serial_number IN (/*SLICE:serials*/?)
`

type DeleteDevicesByDEPAndSerialsParams struct {
	DepName string
	Serials []string
}

func (q *Queries) DeleteDevicesByDEPAndSerials(ctx context.Context, arg DeleteDevicesByDEPAndSerialsParams) error {
	query := deleteDevicesByDEPAndSerials
	var queryParams []any
	queryParams = append(queryParams, arg.DepName)
	if len(arg.Serials) > 0 {
		for _, v := range arg.Serials {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:serials*/?", strings.Repeat(",?", len(arg.Serials))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:serials*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT
    serial_number, dep_name, model, asset_tag, bluetooth_mac_address, color, description, device_assigned_by, device_assigned_date, device_family, eid, ethernet_mac_address, imei, is_replacement_device, mdm_migration_deadline, meid, op_date, op_type, os, profile_assign_time, profile_push_time, profile_status, profile_uuid, released_by_replacement, response_status, wifi_mac_address, created_at, updated_at
FROM
    dep_devices
ORDER BY
    dep_name,
    serial_number
LIMIT
    ? OFFSET ?
`

type ListDevicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]DepDevice, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepDevice
	for rows.Next() {
		var i DepDevice
		if err := rows.Scan(
			&i.SerialNumber,
			&i.DepName,
			&i.Model,
			&i.AssetTag,
			&i.BluetoothMacAddress,
			&i.Color,
			&i.Description,
			&i.DeviceAssignedBy,
			&i.DeviceAssignedDate,
			&i.DeviceFamily,
			&i.Eid,
			&i.EthernetMacAddress,
			&i.Imei,
			&i.IsReplacementDevice,
			&i.MdmMigrationDeadline,
			&i.Meid,
			&i.OpDate,
			&i.OpType,
			&i.Os,
			&i.ProfileAssignTime,
			&i.ProfilePushTime,
			&i.ProfileStatus,
			&i.ProfileUuid,
			&i.ReleasedByReplacement,
			&i.ResponseStatus,
			&i.WifiMacAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByDEP = `-- name: ListDevicesByDEP :many
SELECT
    serial_number, dep_name, model, asset_tag, bluetooth_mac_address, color, description, device_assigned_by, device_assigned_date, device_family, eid, ethernet_mac_address, imei, is_replacement_device, mdm_migration_deadline, meid, op_date, op_type, os, profile_assign_time, profile_push_time, profile_status, profile_uuid, released_by_replacement, response_status, wifi_mac_address, created_at, updated_at
FROM
    dep_devices
WHERE
    dep_name IN (/*SLICE:dep_names*/?)
ORDER BY
    dep_name,
    serial_number
LIMIT
    ? OFFSET ?
`

type ListDevicesByDEPParams struct {
	DepNames []string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListDevicesByDEP(ctx context.Context, arg ListDevicesByDEPParams) ([]DepDevice, error) {
	query := listDevicesByDEP
	var queryParams []any
	if len(arg.DepNames) > 0 {
		for _, v := range arg.DepNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dep_names*/?", strings.Repeat(",?", len(arg.DepNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dep_names*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepDevice
	for rows.Next() {
		var i DepDevice
		if err := rows.Scan(
			&i.SerialNumber,
			&i.DepName,
			&i.Model,
			&i.AssetTag,
			&i.BluetoothMacAddress,
			&i.Color,
			&i.Description,
			&i.DeviceAssignedBy,
			&i.DeviceAssignedDate,
			&i.DeviceFamily,
			&i.Eid,
			&i.EthernetMacAddress,
			&i.Imei,
			&i.IsReplacementDevice,
			&i.MdmMigrationDeadline,
			&i.Meid,
			&i.OpDate,
			&i.OpType,
			&i.Os,
			&i.ProfileAssignTime,
			&i.ProfilePushTime,
			&i.ProfileStatus,
			&i.ProfileUuid,
			&i.ReleasedByReplacement,
			&i.ResponseStatus,
			&i.WifiMacAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByDEPAndSerial = `-- name: ListDevicesByDEPAndSerial :many
SELECT
    serial_number, dep_name, model, asset_tag, bluetooth_mac_address, color, description, device_assigned_by, device_assigned_date, device_family, eid, ethernet_mac_address, imei, is_replacement_device, mdm_migration_deadline, meid, op_date, op_type, os, profile_assign_time, profile_push_time, profile_status, profile_uuid, released_by_replacement, response_status, wifi_mac_address, created_at, updated_at
FROM
    dep_devices
WHERE
    dep_name IN (/*SLICE:dep_names*/?)
    AND serial_number IN (/*SLICE:serials*/?)
ORDER BY
    dep_name,
    serial_number
LIMIT
    ? OFFSET ?
`

type ListDevicesByDEPAndSerialParams struct {
	DepNames []string
	Serials  []string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListDevicesByDEPAndSerial(ctx context.Context, arg ListDevicesByDEPAndSerialParams) ([]DepDevice, error) {
	query := listDevicesByDEPAndSerial
	var queryParams []any
	if len(arg.DepNames) > 0 {
		for _, v := range arg.DepNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dep_names*/?", strings.Repeat(",?", len(arg.DepNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dep_names*/?", "NULL", 1)
	}
	if len(arg.Serials) > 0 {
		for _, v := range arg.Serials {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:serials*/?", strings.Repeat(",?", len(arg.Serials))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:serials*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepDevice
	for rows.Next() {
		var i DepDevice
		if err := rows.Scan(
			&i.SerialNumber,
			&i.DepName,
			&i.Model,
			&i.AssetTag,
			&i.BluetoothMacAddress,
			&i.Color,
			&i.Description,
			&i.DeviceAssignedBy,
			&i.DeviceAssignedDate,
			&i.DeviceFamily,
			&i.Eid,
			&i.EthernetMacAddress,
			&i.Imei,
			&i.IsReplacementDevice,
			&i.MdmMigrationDeadline,
			&i.Meid,
			&i.OpDate,
			&i.OpType,
			&i.Os,
			&i.ProfileAssignTime,
			&i.ProfilePushTime,
			&i.ProfileStatus,
			&i.ProfileUuid,
			&i.ReleasedByReplacement,
			&i.ResponseStatus,
			&i.WifiMacAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesBySerial = `-- name: ListDevicesBySerial :many
SELECT
    serial_number, dep_name, model, asset_tag, bluetooth_mac_address, color, description, device_assigned_by, device_assigned_date, device_family, eid, ethernet_mac_address, imei, is_replacement_device, mdm_migration_deadline, meid, op_date, op_type, os, profile_assign_time, profile_push_time, profile_status, profile_uuid, released_by_replacement, response_status, wifi_mac_address, created_at, updated_at
FROM
    dep_devices
WHERE
    serial_number IN (/*SLICE:serials*/?)
ORDER BY
    dep_name,
    serial_number
LIMIT
    ? OFFSET ?
`

type ListDevicesBySerialParams struct {
	Serials []string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListDevicesBySerial(ctx context.Context, arg ListDevicesBySerialParams) ([]DepDevice, error) {
	query := listDevicesBySerial
	var queryParams []any
	if len(arg.Serials) > 0 {
		for _, v := range arg.Serials {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:serials*/?", strings.Repeat(",?", len(arg.Serials))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:serials*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepDevice
	for rows.Next() {
		var i DepDevice
		if err := rows.Scan(
			&i.SerialNumber,
			&i.DepName,
			&i.Model,
			&i.AssetTag,
			&i.BluetoothMacAddress,
			&i.Color,
			&i.Description,
			&i.DeviceAssignedBy,
			&i.DeviceAssignedDate,
			&i.DeviceFamily,
			&i.Eid,
			&i.EthernetMacAddress,
			&i.Imei,
			&i.IsReplacementDevice,
			&i.MdmMigrationDeadline,
			&i.Meid,
			&i.OpDate,
			&i.OpType,
			&i.Os,
			&i.ProfileAssignTime,
			&i.ProfilePushTime,
			&i.ProfileStatus,
			&i.ProfileUuid,
			&i.ReleasedByReplacement,
			&i.ResponseStatus,
			&i.WifiMacAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO
    dep_devices (
        serial_number,
        dep_name,
        model,
        asset_tag,
        bluetooth_mac_address,
        color,
        description,
        device_assigned_by,
        device_assigned_date,
        device_family,
        eid,
        ethernet_mac_address,
        imei,
        is_replacement_device,
        mdm_migration_deadline,
        meid,
        op_date,
        op_type,
        os,
        profile_assign_time,
        profile_push_time,
        profile_status,
        profile_uuid,
        released_by_replacement,
        response_status,
        wifi_mac_address,
        created_at,
        updated_at
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) AS new ON DUPLICATE KEY
UPDATE
    model = new.model,
    asset_tag = COALESCE(new.asset_tag, dep_devices.asset_tag),
    bluetooth_mac_address = COALESCE(
        new.bluetooth_mac_address,
        dep_devices.bluetooth_mac_address
    ),
    color = COALESCE(new.color, dep_devices.color),
    description = COALESCE(new.description, dep_devices.description),
    device_assigned_by = COALESCE(
        new.device_assigned_by,
        dep_devices.device_assigned_by
    ),
    device_assigned_date = COALESCE(
        new.device_assigned_date,
        dep_devices.device_assigned_date
    ),
    device_family = COALESCE(new.device_family, dep_devices.device_family),
    eid = COALESCE(new.eid, dep_devices.eid),
    ethernet_mac_address = COALESCE(
        new.ethernet_mac_address,
        dep_devices.ethernet_mac_address
    ),
    imei = COALESCE(new.imei, dep_devices.imei),
    is_replacement_device = COALESCE(
        new.is_replacement_device,
        dep_devices.is_replacement_device
    ),
    mdm_migration_deadline = COALESCE(
        new.mdm_migration_deadline,
        dep_devices.mdm_migration_deadline
    ),
    meid = COALESCE(new.meid, dep_devices.meid),
    op_date = COALESCE(new.op_date, dep_devices.op_date),
    op_type = COALESCE(new.op_type, dep_devices.op_type),
    os = COALESCE(new.os, dep_devices.os),
    profile_assign_time = COALESCE(
        new.profile_assign_time,
        dep_devices.profile_assign_time
    ),
    profile_push_time = COALESCE(
        new.profile_push_time,
        dep_devices.profile_push_time
    ),
    profile_status = COALESCE(new.profile_status, dep_devices.profile_status),
    profile_uuid = COALESCE(new.profile_uuid, dep_devices.profile_uuid),
    released_by_replacement = COALESCE(
        new.released_by_replacement,
        dep_devices.released_by_replacement
    ),
    response_status = COALESCE(new.response_status, dep_devices.response_status),
    wifi_mac_address = COALESCE(
        new.wifi_mac_address,
        dep_devices.wifi_mac_address
    ),
    created_at = dep_devices.created_at,
    updated_at = new.updated_at
`

type UpsertDeviceParams struct {
	SerialNumber          string
	DepName               string
	Model                 string
	AssetTag              sql.NullString
	BluetoothMacAddress   sql.NullString
	Color                 sql.NullString
	Description           sql.NullString
	DeviceAssignedBy      sql.NullString
	DeviceAssignedDate    sql.NullInt64
	DeviceFamily          sql.NullString
	Eid                   sql.NullString
	EthernetMacAddress    sql.NullString
	Imei                  []byte
	IsReplacementDevice   sql.NullBool
	MdmMigrationDeadline  sql.NullInt64
	Meid                  []byte
	OpDate                sql.NullInt64
	OpType                sql.NullString
	Os                    sql.NullString
	ProfileAssignTime     sql.NullInt64
	ProfilePushTime       sql.NullInt64
	ProfileStatus         sql.NullString
	ProfileUuid           sql.NullString
	ReleasedByReplacement sql.NullBool
	ResponseStatus        sql.NullString
	WifiMacAddress        sql.NullString
	CreatedAt             uint64
	UpdatedAt             uint64
}

// Upsert a single synced device, NULL-averse: NULL incoming fields
// preserve the stored values (COALESCE), identity columns overwrite.
// Go loops over devices in slice order; wrap the batch in a transaction.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.SerialNumber,
		arg.DepName,
		arg.Model,
		arg.AssetTag,
		arg.BluetoothMacAddress,
		arg.Color,
		arg.Description,
		arg.DeviceAssignedBy,
		arg.DeviceAssignedDate,
		arg.DeviceFamily,
		arg.Eid,
		arg.EthernetMacAddress,
		arg.Imei,
		arg.IsReplacementDevice,
		arg.MdmMigrationDeadline,
		arg.Meid,
		arg.OpDate,
		arg.OpType,
		arg.Os,
		arg.ProfileAssignTime,
		arg.ProfilePushTime,
		arg.ProfileStatus,
		arg.ProfileUuid,
		arg.ReleasedByReplacement,
		arg.ResponseStatus,
		arg.WifiMacAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
