// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package sqlc

import (
	"database/sql"
)

type DepName struct {
	Name                  string
	ConsumerKey           sql.NullString
	ConsumerSecret        sql.NullString
	AccessToken           sql.NullString
	AccessSecret          sql.NullString
	AccessTokenExpiry     sql.NullString
	ConfigBaseUrl         sql.NullString
	TokenpkiCertPem       []byte
	TokenpkiKeyPem        []byte
	SyncerCursor          sql.NullString
	AssignerProfileUuid   sql.NullString
	AssignerProfileUuidAt sql.NullString
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
}
