// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type DepName struct {
	Name                   string
	ConsumerKey            sql.NullString
	ConsumerSecret         sql.NullString
	AccessToken            sql.NullString
	AccessSecret           sql.NullString
	AccessTokenExpiry      sql.NullString
	ConfigBaseUrl          sql.NullString
	TokenpkiCertPem        []byte
	TokenpkiKeyPem         []byte
	TokenpkiStagingCertPem []byte
	TokenpkiStagingKeyPem  []byte
	SyncerCursor           sql.NullString
	AssignerProfileUuid    sql.NullString
	AssignerProfileUuidAt  sql.NullString
	CreatedAt              sql.NullString
	UpdatedAt              sql.NullString
}
