// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const getAllDEPNames = `-- name: GetAllDEPNames :many
SELECT name FROM dep_names WHERE tokenpki_staging_cert_pem IS NOT NULL LIMIT ? OFFSET ?
`

type GetAllDEPNamesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllDEPNames(ctx context.Context, arg GetAllDEPNamesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllDEPNames, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignerProfile = `-- name: GetAssignerProfile :one
SELECT
  assigner_profile_uuid,
  assigner_profile_uuid_at
FROM
  dep_names
WHERE
  name = ?
`

type GetAssignerProfileRow struct {
	AssignerProfileUuid   sql.NullString
	AssignerProfileUuidAt sql.NullString
}

func (q *Queries) GetAssignerProfile(ctx context.Context, name string) (GetAssignerProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getAssignerProfile, name)
	var i GetAssignerProfileRow
	err := row.Scan(&i.AssignerProfileUuid, &i.AssignerProfileUuidAt)
	return i, err
}

const getAuthTokens = `-- name: GetAuthTokens :one
SELECT
  consumer_key,
  consumer_secret,
  access_token,
  access_secret,
  access_token_expiry
FROM
  dep_names
WHERE
  name = ?
`

type GetAuthTokensRow struct {
	ConsumerKey       sql.NullString
	ConsumerSecret    sql.NullString
	AccessToken       sql.NullString
	AccessSecret      sql.NullString
	AccessTokenExpiry sql.NullString
}

func (q *Queries) GetAuthTokens(ctx context.Context, name string) (GetAuthTokensRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthTokens, name)
	var i GetAuthTokensRow
	err := row.Scan(
		&i.ConsumerKey,
		&i.ConsumerSecret,
		&i.AccessToken,
		&i.AccessSecret,
		&i.AccessTokenExpiry,
	)
	return i, err
}

const getConfigBaseURL = `-- name: GetConfigBaseURL :one
SELECT config_base_url FROM dep_names WHERE name = ?
`

func (q *Queries) GetConfigBaseURL(ctx context.Context, name string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getConfigBaseURL, name)
	var config_base_url sql.NullString
	err := row.Scan(&config_base_url)
	return config_base_url, err
}

const getCurrentKeypair = `-- name: GetCurrentKeypair :one
SELECT
  tokenpki_cert_pem,
  tokenpki_key_pem
FROM
  dep_names
WHERE
  name = ?
`

type GetCurrentKeypairRow struct {
	TokenpkiCertPem []byte
	TokenpkiKeyPem  []byte
}

func (q *Queries) GetCurrentKeypair(ctx context.Context, name string) (GetCurrentKeypairRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentKeypair, name)
	var i GetCurrentKeypairRow
	err := row.Scan(&i.TokenpkiCertPem, &i.TokenpkiKeyPem)
	return i, err
}

const getDEPNames = `-- name: GetDEPNames :many
SELECT
  name
FROM
  dep_names
WHERE
  name IN (/*SLICE:dep_names*/?) AND
  tokenpki_staging_cert_pem IS NOT NULL
LIMIT ? OFFSET ?
`

type GetDEPNamesParams struct {
	DepNames []string
	Limit    int32
	Offset   int32
}

func (q *Queries) GetDEPNames(ctx context.Context, arg GetDEPNamesParams) ([]string, error) {
	query := getDEPNames
	var queryParams []any
	if len(arg.DepNames) > 0 {
		for _, v := range arg.DepNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dep_names*/?", strings.Repeat(",?", len(arg.DepNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dep_names*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStagingKeypair = `-- name: GetStagingKeypair :one
SELECT
  tokenpki_staging_cert_pem,
  tokenpki_staging_key_pem
FROM
  dep_names
WHERE
  name = ?
`

type GetStagingKeypairRow struct {
	TokenpkiStagingCertPem []byte
	TokenpkiStagingKeyPem  []byte
}

func (q *Queries) GetStagingKeypair(ctx context.Context, name string) (GetStagingKeypairRow, error) {
	row := q.db.QueryRowContext(ctx, getStagingKeypair, name)
	var i GetStagingKeypairRow
	err := row.Scan(&i.TokenpkiStagingCertPem, &i.TokenpkiStagingKeyPem)
	return i, err
}

const getSyncerCursor = `-- name: GetSyncerCursor :one
SELECT syncer_cursor FROM dep_names WHERE name = ?
`

func (q *Queries) GetSyncerCursor(ctx context.Context, name string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSyncerCursor, name)
	var syncer_cursor sql.NullString
	err := row.Scan(&syncer_cursor)
	return syncer_cursor, err
}

const storeAssignerProfile = `-- name: StoreAssignerProfile :exec
INSERT INTO dep_names
  (name, assigner_profile_uuid, assigner_profile_uuid_at)
VALUES
  (?, ?, CURRENT_TIMESTAMP) AS new
ON DUPLICATE KEY UPDATE
  assigner_profile_uuid = new.assigner_profile_uuid,
  assigner_profile_uuid_at = new.assigner_profile_uuid_at
`

type StoreAssignerProfileParams struct {
	Name                string
	AssignerProfileUuid sql.NullString
}

func (q *Queries) StoreAssignerProfile(ctx context.Context, arg StoreAssignerProfileParams) error {
	_, err := q.db.ExecContext(ctx, storeAssignerProfile, arg.Name, arg.AssignerProfileUuid)
	return err
}

const storeAuthTokens = `-- name: StoreAuthTokens :exec
INSERT INTO dep_names
  (name, consumer_key, consumer_secret, access_token, access_secret, access_token_expiry)
VALUES
  (?, ?, ?, ?, ?, ?) AS new
ON DUPLICATE KEY UPDATE
  consumer_key = new.consumer_key,
  consumer_secret = new.consumer_secret,
  access_token = new.access_token,
  access_secret = new.access_secret,
  access_token_expiry = new.access_token_expiry
`

type StoreAuthTokensParams struct {
	Name              string
	ConsumerKey       sql.NullString
	ConsumerSecret    sql.NullString
	AccessToken       sql.NullString
	AccessSecret      sql.NullString
	AccessTokenExpiry sql.NullString
}

func (q *Queries) StoreAuthTokens(ctx context.Context, arg StoreAuthTokensParams) error {
	_, err := q.db.ExecContext(ctx, storeAuthTokens,
		arg.Name,
		arg.ConsumerKey,
		arg.ConsumerSecret,
		arg.AccessToken,
		arg.AccessSecret,
		arg.AccessTokenExpiry,
	)
	return err
}

const storeConfig = `-- name: StoreConfig :exec
INSERT INTO dep_names
  (name, config_base_url)
VALUES
  (?, ?) AS new
ON DUPLICATE KEY UPDATE
  config_base_url = new.config_base_url
`

type StoreConfigParams struct {
	Name          string
	ConfigBaseUrl sql.NullString
}

func (q *Queries) StoreConfig(ctx context.Context, arg StoreConfigParams) error {
	_, err := q.db.ExecContext(ctx, storeConfig, arg.Name, arg.ConfigBaseUrl)
	return err
}

const storeCursor = `-- name: StoreCursor :exec
INSERT INTO dep_names
  (name, syncer_cursor)
VALUES
  (?, ?) AS new
ON DUPLICATE KEY UPDATE
  syncer_cursor = new.syncer_cursor
`

type StoreCursorParams struct {
	Name         string
	SyncerCursor sql.NullString
}

func (q *Queries) StoreCursor(ctx context.Context, arg StoreCursorParams) error {
	_, err := q.db.ExecContext(ctx, storeCursor, arg.Name, arg.SyncerCursor)
	return err
}

const storeTokenPKI = `-- name: StoreTokenPKI :exec
INSERT INTO dep_names
  (name, tokenpki_staging_cert_pem, tokenpki_staging_key_pem)
VALUES
  (?, ?, ?) AS new
ON DUPLICATE KEY UPDATE
  tokenpki_staging_cert_pem = new.tokenpki_staging_cert_pem,
  tokenpki_staging_key_pem = new.tokenpki_staging_key_pem
`

type StoreTokenPKIParams struct {
	Name                   string
	TokenpkiStagingCertPem []byte
	TokenpkiStagingKeyPem  []byte
}

func (q *Queries) StoreTokenPKI(ctx context.Context, arg StoreTokenPKIParams) error {
	_, err := q.db.ExecContext(ctx, storeTokenPKI, arg.Name, arg.TokenpkiStagingCertPem, arg.TokenpkiStagingKeyPem)
	return err
}

const upstageKeypair = `-- name: UpstageKeypair :exec
UPDATE
  dep_names
SET
  tokenpki_cert_pem = tokenpki_staging_cert_pem,
  tokenpki_key_pem = tokenpki_staging_key_pem
WHERE
  name = ?
`

func (q *Queries) UpstageKeypair(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, upstageKeypair, name)
	return err
}
