// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const deleteDevicesByDEPAndSerials = `-- name: DeleteDevicesByDEPAndSerials :exec
DELETE FROM dep_devices
WHERE dep_name = $1
  AND serial_number = ANY($2::varchar[])
`

type DeleteDevicesByDEPAndSerialsParams struct {
	DepName string
	Serials []string
}

func (q *Queries) DeleteDevicesByDEPAndSerials(ctx context.Context, arg DeleteDevicesByDEPAndSerialsParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevicesByDEPAndSerials, arg.DepName, pq.Array(arg.Serials))
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT serial_number, dep_name, model, asset_tag, bluetooth_mac_address, color, description, device_assigned_by, device_assigned_date, device_family, eid, ethernet_mac_address, imei, is_replacement_device, mdm_migration_deadline, meid, op_date, op_type, os, profile_assign_time, profile_push_time, profile_status, profile_uuid, released_by_replacement, response_status, wifi_mac_address, created_at, updated_at
FROM dep_devices
ORDER BY dep_name, serial_number
LIMIT $1 OFFSET $2
`

type ListDevicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]DepDevice, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepDevice
	for rows.Next() {
		var i DepDevice
		if err := rows.Scan(
			&i.SerialNumber,
			&i.DepName,
			&i.Model,
			&i.AssetTag,
			&i.BluetoothMacAddress,
			&i.Color,
			&i.Description,
			&i.DeviceAssignedBy,
			&i.DeviceAssignedDate,
			&i.DeviceFamily,
			&i.Eid,
			&i.EthernetMacAddress,
			&i.Imei,
			&i.IsReplacementDevice,
			&i.MdmMigrationDeadline,
			&i.Meid,
			&i.OpDate,
			&i.OpType,
			&i.Os,
			&i.ProfileAssignTime,
			&i.ProfilePushTime,
			&i.ProfileStatus,
			&i.ProfileUuid,
			&i.ReleasedByReplacement,
			&i.ResponseStatus,
			&i.WifiMacAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByDEP = `-- name: ListDevicesByDEP :many
SELECT serial_number, dep_name, model, asset_tag, bluetooth_mac_address, color, description, device_assigned_by, device_assigned_date, device_family, eid, ethernet_mac_address, imei, is_replacement_device, mdm_migration_deadline, meid, op_date, op_type, os, profile_assign_time, profile_push_time, profile_status, profile_uuid, released_by_replacement, response_status, wifi_mac_address, created_at, updated_at
FROM dep_devices
WHERE dep_name = ANY($3::varchar[])
ORDER BY dep_name, serial_number
LIMIT $1 OFFSET $2
`

type ListDevicesByDEPParams struct {
	Limit    int32
	Offset   int32
	DepNames []string
}

func (q *Queries) ListDevicesByDEP(ctx context.Context, arg ListDevicesByDEPParams) ([]DepDevice, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByDEP, arg.Limit, arg.Offset, pq.Array(arg.DepNames))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepDevice
	for rows.Next() {
		var i DepDevice
		if err := rows.Scan(
			&i.SerialNumber,
			&i.DepName,
			&i.Model,
			&i.AssetTag,
			&i.BluetoothMacAddress,
			&i.Color,
			&i.Description,
			&i.DeviceAssignedBy,
			&i.DeviceAssignedDate,
			&i.DeviceFamily,
			&i.Eid,
			&i.EthernetMacAddress,
			&i.Imei,
			&i.IsReplacementDevice,
			&i.MdmMigrationDeadline,
			&i.Meid,
			&i.OpDate,
			&i.OpType,
			&i.Os,
			&i.ProfileAssignTime,
			&i.ProfilePushTime,
			&i.ProfileStatus,
			&i.ProfileUuid,
			&i.ReleasedByReplacement,
			&i.ResponseStatus,
			&i.WifiMacAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByDEPAndSerial = `-- name: ListDevicesByDEPAndSerial :many
SELECT serial_number, dep_name, model, asset_tag, bluetooth_mac_address, color, description, device_assigned_by, device_assigned_date, device_family, eid, ethernet_mac_address, imei, is_replacement_device, mdm_migration_deadline, meid, op_date, op_type, os, profile_assign_time, profile_push_time, profile_status, profile_uuid, released_by_replacement, response_status, wifi_mac_address, created_at, updated_at
FROM dep_devices
WHERE dep_name = ANY($3::varchar[])
  AND serial_number = ANY($4::varchar[])
ORDER BY dep_name, serial_number
LIMIT $1 OFFSET $2
`

type ListDevicesByDEPAndSerialParams struct {
	Limit    int32
	Offset   int32
	DepNames []string
	Serials  []string
}

func (q *Queries) ListDevicesByDEPAndSerial(ctx context.Context, arg ListDevicesByDEPAndSerialParams) ([]DepDevice, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByDEPAndSerial,
		arg.Limit,
		arg.Offset,
		pq.Array(arg.DepNames),
		pq.Array(arg.Serials),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepDevice
	for rows.Next() {
		var i DepDevice
		if err := rows.Scan(
			&i.SerialNumber,
			&i.DepName,
			&i.Model,
			&i.AssetTag,
			&i.BluetoothMacAddress,
			&i.Color,
			&i.Description,
			&i.DeviceAssignedBy,
			&i.DeviceAssignedDate,
			&i.DeviceFamily,
			&i.Eid,
			&i.EthernetMacAddress,
			&i.Imei,
			&i.IsReplacementDevice,
			&i.MdmMigrationDeadline,
			&i.Meid,
			&i.OpDate,
			&i.OpType,
			&i.Os,
			&i.ProfileAssignTime,
			&i.ProfilePushTime,
			&i.ProfileStatus,
			&i.ProfileUuid,
			&i.ReleasedByReplacement,
			&i.ResponseStatus,
			&i.WifiMacAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesBySerial = `-- name: ListDevicesBySerial :many
SELECT serial_number, dep_name, model, asset_tag, bluetooth_mac_address, color, description, device_assigned_by, device_assigned_date, device_family, eid, ethernet_mac_address, imei, is_replacement_device, mdm_migration_deadline, meid, op_date, op_type, os, profile_assign_time, profile_push_time, profile_status, profile_uuid, released_by_replacement, response_status, wifi_mac_address, created_at, updated_at
FROM dep_devices
WHERE serial_number = ANY($3::varchar[])
ORDER BY dep_name, serial_number
LIMIT $1 OFFSET $2
`

type ListDevicesBySerialParams struct {
	Limit   int32
	Offset  int32
	Serials []string
}

func (q *Queries) ListDevicesBySerial(ctx context.Context, arg ListDevicesBySerialParams) ([]DepDevice, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesBySerial, arg.Limit, arg.Offset, pq.Array(arg.Serials))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepDevice
	for rows.Next() {
		var i DepDevice
		if err := rows.Scan(
			&i.SerialNumber,
			&i.DepName,
			&i.Model,
			&i.AssetTag,
			&i.BluetoothMacAddress,
			&i.Color,
			&i.Description,
			&i.DeviceAssignedBy,
			&i.DeviceAssignedDate,
			&i.DeviceFamily,
			&i.Eid,
			&i.EthernetMacAddress,
			&i.Imei,
			&i.IsReplacementDevice,
			&i.MdmMigrationDeadline,
			&i.Meid,
			&i.OpDate,
			&i.OpType,
			&i.Os,
			&i.ProfileAssignTime,
			&i.ProfilePushTime,
			&i.ProfileStatus,
			&i.ProfileUuid,
			&i.ReleasedByReplacement,
			&i.ResponseStatus,
			&i.WifiMacAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO dep_devices (
  serial_number, dep_name, model,
  asset_tag, bluetooth_mac_address, color, description,
  device_assigned_by, device_assigned_date, device_family,
  eid, ethernet_mac_address, imei, is_replacement_device,
  mdm_migration_deadline, meid, op_date, op_type, os,
  profile_assign_time, profile_push_time, profile_status,
  profile_uuid, released_by_replacement, response_status,
  wifi_mac_address, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
  $21, $22, $23, $24, $25, $26, $27, $28
) ON CONFLICT (dep_name, serial_number) DO UPDATE SET
  model = excluded.model,
  asset_tag = COALESCE(excluded.asset_tag, dep_devices.asset_tag),
  bluetooth_mac_address = COALESCE(excluded.bluetooth_mac_address, dep_devices.bluetooth_mac_address),
  color = COALESCE(excluded.color, dep_devices.color),
  description = COALESCE(excluded.description, dep_devices.description),
  device_assigned_by = COALESCE(excluded.device_assigned_by, dep_devices.device_assigned_by),
  device_assigned_date = COALESCE(excluded.device_assigned_date, dep_devices.device_assigned_date),
  device_family = COALESCE(excluded.device_family, dep_devices.device_family),
  eid = COALESCE(excluded.eid, dep_devices.eid),
  ethernet_mac_address = COALESCE(excluded.ethernet_mac_address, dep_devices.ethernet_mac_address),
  imei = COALESCE(excluded.imei, dep_devices.imei),
  is_replacement_device = COALESCE(excluded.is_replacement_device, dep_devices.is_replacement_device),
  mdm_migration_deadline = COALESCE(excluded.mdm_migration_deadline, dep_devices.mdm_migration_deadline),
  meid = COALESCE(excluded.meid, dep_devices.meid),
  op_date = COALESCE(excluded.op_date, dep_devices.op_date),
  op_type = COALESCE(excluded.op_type, dep_devices.op_type),
  os = COALESCE(excluded.os, dep_devices.os),
  profile_assign_time = COALESCE(excluded.profile_assign_time, dep_devices.profile_assign_time),
  profile_push_time = COALESCE(excluded.profile_push_time, dep_devices.profile_push_time),
  profile_status = COALESCE(excluded.profile_status, dep_devices.profile_status),
  profile_uuid = COALESCE(excluded.profile_uuid, dep_devices.profile_uuid),
  released_by_replacement = COALESCE(excluded.released_by_replacement, dep_devices.released_by_replacement),
  response_status = COALESCE(excluded.response_status, dep_devices.response_status),
  wifi_mac_address = COALESCE(excluded.wifi_mac_address, dep_devices.wifi_mac_address),
  created_at = dep_devices.created_at,
  updated_at = excluded.updated_at
`

type UpsertDeviceParams struct {
	SerialNumber          string
	DepName               string
	Model                 string
	AssetTag              sql.NullString
	BluetoothMacAddress   sql.NullString
	Color                 sql.NullString
	Description           sql.NullString
	DeviceAssignedBy      sql.NullString
	DeviceAssignedDate    sql.NullInt64
	DeviceFamily          sql.NullString
	Eid                   sql.NullString
	EthernetMacAddress    sql.NullString
	Imei                  []byte
	IsReplacementDevice   sql.NullBool
	MdmMigrationDeadline  sql.NullInt64
	Meid                  []byte
	OpDate                sql.NullInt64
	OpType                sql.NullString
	Os                    sql.NullString
	ProfileAssignTime     sql.NullInt64
	ProfilePushTime       sql.NullInt64
	ProfileStatus         sql.NullString
	ProfileUuid           sql.NullString
	ReleasedByReplacement sql.NullBool
	ResponseStatus        sql.NullString
	WifiMacAddress        sql.NullString
	CreatedAt             int64
	UpdatedAt             int64
}

// Upsert a single synced device, NULL-averse: NULL incoming fields
// preserve the stored values (COALESCE), identity columns overwrite.
// Go loops over devices in slice order; wrap the batch in a transaction.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.SerialNumber,
		arg.DepName,
		arg.Model,
		arg.AssetTag,
		arg.BluetoothMacAddress,
		arg.Color,
		arg.Description,
		arg.DeviceAssignedBy,
		arg.DeviceAssignedDate,
		arg.DeviceFamily,
		arg.Eid,
		arg.EthernetMacAddress,
		arg.Imei,
		arg.IsReplacementDevice,
		arg.MdmMigrationDeadline,
		arg.Meid,
		arg.OpDate,
		arg.OpType,
		arg.Os,
		arg.ProfileAssignTime,
		arg.ProfilePushTime,
		arg.ProfileStatus,
		arg.ProfileUuid,
		arg.ReleasedByReplacement,
		arg.ResponseStatus,
		arg.WifiMacAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
