CREATE TABLE dep_devices (
    serial_number VARCHAR(255) NOT NULL,
    dep_name VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,

    asset_tag VARCHAR(255) NULL,
    bluetooth_mac_address VARCHAR(255) NULL,
    color VARCHAR(255) NULL,
    description VARCHAR(255) NULL,
    device_assigned_by VARCHAR(255) NULL,
    device_assigned_date BIGINT UNSIGNED NULL,
    device_family VARCHAR(255) NULL,
    eid VARCHAR(255) NULL,
    ethernet_mac_address VARCHAR(255) NULL,
    imei JSON NULL,
    is_replacement_device BOOLEAN NULL,
    mdm_migration_deadline BIGINT UNSIGNED NULL,
    meid JSON NULL,
    op_date BIGINT UNSIGNED NULL,
    op_type VARCHAR(255) NULL,
    os VARCHAR(255) NULL,
    profile_assign_time BIGINT UNSIGNED NULL,
    profile_push_time BIGINT UNSIGNED NULL,
    profile_status VARCHAR(255) NULL,
    profile_uuid VARCHAR(255) NULL,
    released_by_replacement BOOLEAN NULL,
    response_status VARCHAR(255) NULL,
    wifi_mac_address VARCHAR(255) NULL,

    created_at BIGINT UNSIGNED NOT NULL,
    updated_at BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY (dep_name, serial_number),
    INDEX idx_dep_devices_serial (serial_number)
);
